# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: itsjohndevapps
# "service" is the name of this project. This will also be added to your AWS resource names.
service: productService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-2
  httpApi:
    authorizers:
      myCognitoAuth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_qvIf5SjpX
        audience:
          - 14k0ipvkhskvm5bdvsa65kklm9
  environment:
    BUCKET_NAME: product-image-commerce
    DYNAMO_TABLE: Products
    SNS_TOPIC_ARN: arn:aws:sns:ap-southeast-2:032844083309:ProductCleanupTopic
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::product-image-commerce/*
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:Scan"
        - "dynamodb:DeleteItem"
      Resource: arn:aws:dynamodb:ap-southeast-2:032844083309:table/Products
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:ap-southeast-2:032844083309:ProductCleanupTopic

  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
resources:
  Resources:
    ProductImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: product-image-commerce
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    ProductCleanupTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProductCleanupTopic
    ProductCleanupSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: arn:aws:sns:ap-southeast-2:032844083309:ProductCleanupTopic
        Protocol: email
        Endpoint: johncarloaguilar.pinlac@gmail.com

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
          authorizer:
            name: myCognitoAuth
  updateProductImage:
    handler: handlers/updateProductImage.updateProductImage
    events:
      - s3:
          bucket: product-image-commerce
          event: s3:ObjectCreated:Put
          existing: true
  cleanupProducts:
    handler: handlers/cleanupProducts.cleanupProducts
    events:
      - schedule: rate(15 minutes)
